SUCCESS_DELETE_MESSAGE = "Объявление удалено успешно"
DUPLICATE_EMAIL_ERROR_MESSAGE = "Почта уже используется"

SUCCESS_AD_CREATION_CODE = 201
SUCCESS_CODE = 200
AUTHORISED_CODE = 201
UNAUTHORISED_CODE = 401
BAD_REQUEST_CODE = 400
